-- MySQL Script generated by MySQL Workbench
-- Sun Jun  1 18:46:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbLovelyModa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbLovelyModa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbLovelyModa` DEFAULT CHARACTER SET utf8 ;
USE `dbLovelyModa` ;

-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Persona` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_tCliente_tPersona_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_tCliente_tPersona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `dbLovelyModa`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fechaAlta` DATE NULL,
  `fechaBaja` DATE NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_tUsuario_tPersona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_tUsuario_tPersona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `dbLovelyModa`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Venta` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `monto` DOUBLE NULL,
  `moneda` VARCHAR(3) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `cuotas` INT NULL,
  `montoCuota` DOUBLE NULL,
  `tipoVenta` VARCHAR(45) NULL,
  PRIMARY KEY (`idVenta`, `Cliente_idCliente`),
  INDEX `fk_tVenta_tCliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_tVenta_tCliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `dbLovelyModa`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `puntoPedido` INT NULL,
  `loteMinimo` INT NULL,
  `stock` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `caracteristicas` VARCHAR(45) NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`idInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Producto` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL NULL,
  `subtotal` DECIMAL NULL,
  `caracteristicas` VARCHAR(45) NULL,
  `Venta_idVenta` INT NOT NULL,
  `Venta_Cliente_idCliente` INT NOT NULL,
  `Venta_Producto_idProducto` INT NOT NULL,
  `Inventario_idInventario` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Venta_idVenta`, `Venta_Cliente_idCliente`, `Venta_Producto_idProducto`, `Inventario_idInventario`),
  INDEX `fk_Producto_Venta1_idx` (`Venta_idVenta` ASC, `Venta_Cliente_idCliente` ASC, `Venta_Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Producto_Inventario1_idx` (`Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Venta1`
    FOREIGN KEY (`Venta_idVenta` , `Venta_Cliente_idCliente`)
    REFERENCES `dbLovelyModa`.`Venta` (`idVenta` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `dbLovelyModa`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`MovimientoContable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`MovimientoContable` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`MovimientoContable` (
  `idMovimientoContable` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `monto` DOUBLE NULL,
  `moneda` VARCHAR(3) NULL,
  PRIMARY KEY (`idMovimientoContable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Cobro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Cobro` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Cobro` (
  `idCobro` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `monto` DOUBLE NULL,
  `moneda` VARCHAR(3) NULL,
  `Venta_Producto_idProducto` INT NOT NULL,
  `MovimientoContable_idMovimientoContable` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `Venta_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCobro`, `Venta_Producto_idProducto`, `MovimientoContable_idMovimientoContable`, `Venta_idVenta`, `Venta_Cliente_idCliente`),
  INDEX `fk_Cobro_MovimientoContable1_idx` (`MovimientoContable_idMovimientoContable` ASC) VISIBLE,
  INDEX `fk_Cobro_Venta1_idx` (`Venta_idVenta` ASC, `Venta_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cobro_MovimientoContable1`
    FOREIGN KEY (`MovimientoContable_idMovimientoContable`)
    REFERENCES `dbLovelyModa`.`MovimientoContable` (`idMovimientoContable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cobro_Venta1`
    FOREIGN KEY (`Venta_idVenta` , `Venta_Cliente_idCliente`)
    REFERENCES `dbLovelyModa`.`Venta` (`idVenta` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLovelyModa`.`Parametro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLovelyModa`.`Parametro` ;

CREATE TABLE IF NOT EXISTS `dbLovelyModa`.`Parametro` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `parametro` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`idParametro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
